// Generated by CoffeeScript 1.6.2
var cookieCommand, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

cookieCommand = (function(_super) {
  __extends(cookieCommand, _super);

  function cookieCommand() {
    _ref = cookieCommand.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  cookieCommand.prototype.init = function() {
    this.command = 'cookie';
    this.parseType = 'startsWith';
    return this.rankPrivelege = 'featured';
  };

  cookieCommand.prototype.getCookie = function() {
    var c, cookies;

    cookies = ["un cookie au chocolat", "un cookie au sucre", "un cookie au raisin sec", "un brownie chocolat/noisette", "une poche d'haribo", "un scooby snack", "un muffin a la cerise", "une glace"];
    c = Math.floor(Math.random() * cookies.length);
    return cookies[c];
  };

  cookieCommand.prototype.functionality = function() {
    var msg, r, user;

    msg = this.msgData.message;
    r = new RoomHelper();
    if (msg.substring(7, 8) === "@") {
      user = r.lookupUser(msg.substr(8));
      if (user === false) {
        API.sendChat("/em ne trouve pas '" + msg.substr(8) + "' dans la room et mange lui même le cookie");
        return false;
      } else {
        return API.sendChat("@" + user.username + ", @" + this.msgData.from + " t'as recompensé avec " + this.getCookie() + ". Enjoy.");
      }
    }
  };

  return cookieCommand;

})(Command);
