// Generated by CoffeeScript 1.6.2
var rulesCommand, _ref,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

rulesCommand = (function(_super) {
  __extends(rulesCommand, _super);

  function rulesCommand() {
    _ref = rulesCommand.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  rulesCommand.prototype.init = function() {
    this.command = '/rules';
    this.parseType = 'startsWith';
    return this.rankPrivelege = 'featured';
  };

  rulesCommand.prototype.functionality = function() {
    var msg;

    msg = "1) Tous les styles sont autorisés tant qu'ils plaisent. ";
    msg += "2) Evitez les musiques déjà dans l'historique. 3) La limite de durée est de 6 minutes. ";
    msg += "4) Restez actif dans le chat pour ne pas être sorti de la scène!";
    return API.sendChat(msg);
  };

  return rulesCommand;

})(Command);
