// Generated by CoffeeScript 1.4.0
var afkCheck, msToStr;

afkCheck = function() {
  var DJs, id, lastActivity, lastWarned, now, oneMinute, secsLastActive, timeSinceLastActivity, timeSinceLastWarning, twoMinutes, user, warnMsg, _ref, _results;
  _ref = data.users;
  _results = [];
  for (id in _ref) {
    user = _ref[id];
    now = new Date();
    lastActivity = user.getLastActivity();
    timeSinceLastActivity = now.getTime() - lastActivity.getTime();
    if (timeSinceLastActivity > data.afkTime) {
      if (user.getIsDj()) {
        secsLastActive = timeSinceLastActivity / 1000;
        if (user.getWarningCount() === 0) {
          user.warn();
          _results.push(API.sendChat("@" + user.getUser().username + ", Je ne t'ai pas vu écrire depuis 1heure, es tu AFK ? Tu seras sorti dans la scène dans 5 minutes si tu restes inactif dans le chat."));
        } else if (user.getWarningCount() === 1) {
          lastWarned = user.getLastWarning();
          timeSinceLastWarning = now.getTime() - lastWarned.getTime();
          twoMinutes = 5 * 60 * 1000;
          if (timeSinceLastWarning > twoMinutes) {
            user.warn();
          } else {
            _results.push(void 0);
          }
        } else if (user.getWarningCount() === 2) {
          lastWarned = user.getLastWarning();
          timeSinceLastWarning = now.getTime() - lastWarned.getTime();
          oneMinute = 1000;
          if (timeSinceLastWarning > oneMinute) {
            DJs = API.getDJs();
            if (DJs.length > 0 && DJs[0].id !== user.getUser().id) {
              API.sendChat("@" + user.getUser().username + ", tu avais été prévenu, restes actif dans le chat la prochaine fois.");
              API.moderateRemoveDJ(id);
              _results.push(user.warn());
            } else {
              _results.push(void 0);
            }
          } else {
            _results.push(void 0);
          }
        } else {
          _results.push(void 0);
        }
      } else {
        _results.push(user.notDj());
      }
    } else {
      _results.push(void 0);
    }
  }
  return _results;
};

msToStr = function(msTime) {
  var ms, msg, timeAway;
  msg = '';
  timeAway = {
    'days': 0,
    'hours': 0,
    'minutes': 0,
    'seconds': 0
  };
  ms = {
    'day': 24 * 60 * 60 * 1000,
    'hour': 60 * 60 * 1000,
    'minute': 60 * 1000,
    'second': 1000
  };
  if (msTime > ms['day']) {
    timeAway['days'] = Math.floor(msTime / ms['day']);
    msTime = msTime % ms['day'];
  }
  if (msTime > ms['hour']) {
    timeAway['hours'] = Math.floor(msTime / ms['hour']);
    msTime = msTime % ms['hour'];
  }
  if (msTime > ms['minute']) {
    timeAway['minutes'] = Math.floor(msTime / ms['minute']);
    msTime = msTime % ms['minute'];
  }
  if (msTime > ms['second']) {
    timeAway['seconds'] = Math.floor(msTime / ms['second']);
  }
  if (timeAway['days'] !== 0) {
    msg += timeAway['days'].toString() + 'd';
  }
  if (timeAway['hours'] !== 0) {
    msg += timeAway['hours'].toString() + 'h';
  }
  if (timeAway['minutes'] !== 0) {
    msg += timeAway['minutes'].toString() + 'm';
  }
  if (timeAway['seconds'] !== 0) {
    msg += timeAway['seconds'].toString() + 's';
  }
  if (msg !== '') {
    return msg;
  } else {
    return false;
  }
};
